name: CI

on: [push, pull_request]

jobs:
  ci:
    name: ${{ matrix.name }}
    runs-on: ubuntu-20.04

    env:
      CTEST_OUTPUT_ON_FAILURE: ON
      CTEST_PARALLEL_LEVEL: 2

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: gcc
            compiler: gcc
            version: 10

          - name: clang
            compiler: clang
            version: 12

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install
        run: |
          pip install cmake==3.21.4 ninja==1.10.2.2 --upgrade
          sudo apt update
          sudo apt install libxrandr-dev libgl-dev libudev-dev
          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            echo "CC=gcc-${{ matrix.version }}" >> $GITHUB_ENV
            echo "CXX=g++-${{ matrix.version }}" >> $GITHUB_ENV
          else
            echo "CC=clang-${{ matrix.version }}" >> $GITHUB_ENV
            echo "CXX=clang++-${{ matrix.version }}" >> $GITHUB_ENV
          fi

      - name: CMake
        run: cmake -S . -B build -G Ninja

      - name: Build
        run: cmake --build build
